#!/usr/bin/with-contenv bash
#shellcheck shell=bash

SN=$(grep -E "^sn=.*$" /etc/rbfeeder.ini)
MLAT_SN=$(echo "$SN" | cut -d "=" -f 2 | tr -d " ")

if [[ -z "$MLAT_SN" ]]; then
  echo "[mlat-client] Delaying mlat-client startup until rbfeeder receives station sn..."
  sleep 30
  exit 1
fi

exec /usr/local/bin/mlat-client \
    --input-type dump1090 \
    --input-connect "${BEAST_HOST}:${BEAST_PORT}" \
    --results beast,listen,30105 \
    --lat "${LATITUDE}" \
    --lon "${LONGITUDE}" \
    --alt "${ALTITUDE}m" \
    --user "${MLAT_SN}" \
    --server mlat1.rb24.com:40900 \
    2>&1 | mawk -W Interactive '{print "[mlat-client] " $0}'
