#!/usr/bin/with-contenv bash
# shellcheck shell=bash

EXITCODE=0

# Set up timezone
if [ -z "${TZ}" ]; then
  echo -e "WARNING: TZ environment variable not set"
else
  ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime && echo "$TZ" > /etc/timezone
fi
# BeastHost
if [ -z "${BEAST_HOST}" ]; then
  echo -e "ERROR: BEAST_HOST environment variable not set"
  EXITCODE=1
fi
# Handle "-e LATITUDE"
if [ -z "${LATITUDE}" ]; then
  echo -e "ERROR: LATITUDE environment variable not set"
  EXITCODE=1
fi
# Handle "-e LONGITUDE"
if [ -z "${LONGITUDE}" ]; then
  echo -e "ERROR: LONGITUDE environment variable not set"
  EXITCODE=1
fi
# Handle "-e ALTITUDE"
if [ -z "${ALTITUDE}" ]; then
  echo -e "$ERROR: ALTITUDE environment variable not set"
  EXITCODE=1
fi
# Handle "-e RBFEEDER_KEY"
if [ -z "${RBFEEDER_KEY}" ]; then
  echo ""
  echo "WARNING: RBFEEDER_KEY environment variable was not set!"
  echo "Please make sure you note down the key generated."
  echo "Pass the key as environment var RBFEEDER_KEY on next launch!"
  echo ""
fi

# All is good ?
if [ $EXITCODE == 0 ]; then
  # shellcheck disable=SC2153
  echo -e "INFO: Connect to ${BEAST_HOST}:${BEAST_PORT}"
fi

exit $EXITCODE
