#!/usr/bin/with-contenv bash
# shellcheck shell=bash

mkdir -p /var/log/mlat-client
chown nobody:nogroup /var/log/mlat-client

mkdir -p /var/log/rbfeeder
chown nobody:nogroup /var/log/rbfeeder

touch /var/log/rbfeeder.log
truncate --size=0 /var/log/rbfeeder.log
